# ===================================
#  Relation Behavior Config
# ===================================

images:
    label: картинку
    view:
        form: $/pp/kistochki/models/image/fields.yaml
        list: $/pp/kistochki/models/image/columns.yaml
    manage:
        form: $/pp/kistochki/models/image/fields.yaml
        list: $/pp/kistochki/models/image/columns.yaml
tags:
    label: тега
    view:
        form: $/pp/kistochki/models/tag/fields.yaml
        list: $/pp/kistochki/models/tag/columns.yaml
    manage:
        form: $/pp/kistochki/models/tag/fields.yaml
        list: $/pp/kistochki/models/tag/columns.yaml
categories:
    label: категории
    view:
        form: $/pp/kistochki/models/category/fields.yaml
        list: $/pp/kistochki/models/category/columns.yaml
    manage:
        form: $/pp/kistochki/models/category/fields.yaml
        list: $/pp/kistochki/models/category/columns.yaml
price:
    label: Цены
    deferredBinding: true
    view:
        toolbarButtons: create|update|delete
        form: $/pp/kistochki/models/price/fields.yaml
        list: $/pp/kistochki/models/price/columns.yaml
    manage:
        form: $/pp/kistochki/models/price/fields.yaml
        list: $/pp/kistochki/models/price/columns.yaml