list: $/pp/kistochki/models/hit/columns.yaml
modelClass: Pp\Kistochki\Models\Hit
title: Hits
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pp/kistochki/hits/update/:id'
