list: $/pp/kistochki/models/districtcategory/columns.yaml
modelClass: Pp\Kistochki\Models\DistrictCategory
title: DistrictCategories
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pp/kistochki/districtcategories/update/:id'
