list: $/pp/kistochki/models/districtstation/columns.yaml
modelClass: Pp\Kistochki\Models\DistrictStation
title: DistrictStations
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pp/kistochki/districtstations/update/:id'
