list: $/pp/kistochki/models/district/columns.yaml
modelClass: Pp\Kistochki\Models\District
title: Districts
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pp/kistochki/districts/update/:id'
