name: Posts
form: $/pp/kistochki/models/post/post_fields.yaml
modelClass: Pp\Kistochki\Models\Post
defaultRedirect: pp/kistochki/posts
create:
    redirect: 'pp/kistochki/posts/update/:id'
    redirectClose: pp/kistochki/posts
update:
    redirect: pp/kistochki/posts
    redirectClose: pp/kistochki/posts
