list: $/pp/kistochki/models/post/posts_columns.yaml
modelClass: Pp\Kistochki\Models\Post
title: Posts
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pp/kistochki/posts/update/:id'
customViewPath: $/pp/kistochki/controllers/posts/list_override
