# ===================================
#  Relation Behavior Config
# ===================================

images:
    label: картинку
    view:
        form: $/pp/kistochki/models/image/fields.yaml
        list: $/pp/kistochki/models/image/columns.yaml
    manage:
        form: $/pp/kistochki/models/image/fields.yaml
        list: $/pp/kistochki/models/image/columns.yaml