list: $/pp/kistochki/models/districtline/columns.yaml
modelClass: Pp\Kistochki\Models\DistrictLine
title: DistrictLines
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pp/kistochki/districtlines/update/:id'
