list: $/pp/kistochki/models/portfolio/columns.yaml
modelClass: Pp\Kistochki\Models\Portfolio
title: Portfolios
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
showSorting: 1
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pp/kistochki/portfolios/update/:id'
