list: $/pp/kistochki/models/city/columns.yaml
modelClass: Pp\Kistochki\Models\City
title: Cities
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pp/kistochki/cities/update/:id'
