list: $/pp/kistochki/models/callback/columns.yaml
modelClass: Pp\Kistochki\Models\Callback
title: Callbacks
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
