list: $/pp/kistochki/models/menu/columns.yaml
modelClass: Pp\Kistochki\Models\Menu
title: Menus
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pp/kistochki/menus/update/:id'
