list: $/pp/kistochki/models/slider/columns.yaml
modelClass: Pp\Kistochki\Models\Slider
title: Sliders
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
filter: config_filter.yaml
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pp/kistochki/sliders/update/:id'
