scopes:
  cities:
    label: Город
    modelClass: Pp\Kistochki\Models\City
    conditions: city_id in (:filtered)
    nameFrom: title
  status:
    label: Статус
    type: switch
    conditions:
        - status <> true
        - status = true