list: $/pp/kistochki/models/tag/columns.yaml
modelClass: Pp\Kistochki\Models\Tag
title: Tags
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pp/kistochki/tags/update/:id'
